"""add_missing_tables

Revision ID: aceedef7b469
Revises: b8a73e6cc6bf
Create Date: 2026-01-06 07:16:43.078074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aceedef7b469'
down_revision: Union[str, None] = 'b8a73e6cc6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hsn_master',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hsn_code')
    )
    op.create_table('medicine_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['medicine_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unit_master',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('application_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('feature_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('enabled_for', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('file_uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_entity', 'file_uploads', ['entity_type', 'entity_id'], unique=False)
    op.create_table('medicine_pricing_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('old_mrp', sa.Float(), nullable=False),
    sa.Column('new_mrp', sa.Float(), nullable=False),
    sa.Column('old_purchase_price', sa.Float(), nullable=False),
    sa.Column('new_purchase_price', sa.Float(), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_thresholds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_threshold', 'stock_thresholds', ['location_type', 'location_id', 'medicine_id'], unique=False)
    op.create_table('expiry_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('days_to_expiry', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_adjustments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('adjustment_number', sa.String(length=50), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('adjustment_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('adjusted_by', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adjusted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adjustment_number')
    )
    op.create_table('warehouse_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('auto_dispatch', sa.Boolean(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('expiry_alert_days', sa.Integer(), nullable=True),
    sa.Column('working_hours_start', sa.String(length=10), nullable=True),
    sa.Column('working_hours_end', sa.String(length=10), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id')
    )
    op.create_table('billing_sequences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_type', sa.String(length=20), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=True),
    sa.Column('fiscal_year', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['medical_shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_billing_seq', 'billing_sequences', ['shop_id', 'sequence_type', 'fiscal_year'], unique=True)
    op.create_table('gst_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('total_taxable', sa.Float(), nullable=True),
    sa.Column('total_cgst', sa.Float(), nullable=True),
    sa.Column('total_sgst', sa.Float(), nullable=True),
    sa.Column('total_igst', sa.Float(), nullable=True),
    sa.Column('total_tax', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.Column('arn_number', sa.String(length=50), nullable=True),
    sa.Column('report_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['medical_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_expense',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=True),
    sa.Column('warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['medical_shops.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('debit_amount', sa.Float(), nullable=True),
    sa.Column('credit_amount', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['medical_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_date', 'ledger_entries', ['shop_id', 'entry_date'], unique=False)
    op.create_table('shop_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=True),
    sa.Column('invoice_start_number', sa.Integer(), nullable=True),
    sa.Column('tax_inclusive', sa.Boolean(), nullable=True),
    sa.Column('allow_credit_sales', sa.Boolean(), nullable=True),
    sa.Column('max_credit_limit', sa.Float(), nullable=True),
    sa.Column('receipt_footer', sa.Text(), nullable=True),
    sa.Column('working_hours_start', sa.String(length=10), nullable=True),
    sa.Column('working_hours_end', sa.String(length=10), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['medical_shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id')
    )
    op.create_table('tax_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=True),
    sa.Column('tax_type', sa.String(length=20), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('default_rate', sa.Float(), nullable=True),
    sa.Column('is_tax_inclusive', sa.Boolean(), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['medical_shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vat_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Float(), nullable=True),
    sa.Column('total_purchases', sa.Float(), nullable=True),
    sa.Column('output_vat', sa.Float(), nullable=True),
    sa.Column('input_vat', sa.Float(), nullable=True),
    sa.Column('net_vat', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.Column('report_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['medical_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_shop_map',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['medical_shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wh_shop_map', 'warehouse_shop_map', ['warehouse_id', 'shop_id'], unique=True)
    op.create_table('customer_activity_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.Text(), nullable=False),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('esi_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('gross_wages', sa.Float(), nullable=False),
    sa.Column('employee_contribution', sa.Float(), nullable=False),
    sa.Column('employer_contribution', sa.Float(), nullable=False),
    sa.Column('total_contribution', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('deposited_at', sa.DateTime(), nullable=True),
    sa.Column('challan_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_esi_period', 'esi_records', ['employee_id', 'year', 'month'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pf_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('basic_wages', sa.Float(), nullable=False),
    sa.Column('employee_contribution', sa.Float(), nullable=False),
    sa.Column('employer_contribution', sa.Float(), nullable=False),
    sa.Column('total_contribution', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('deposited_at', sa.DateTime(), nullable=True),
    sa.Column('challan_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pf_period', 'pf_records', ['employee_id', 'year', 'month'], unique=False)
    op.create_table('sales_performance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Float(), nullable=True),
    sa.Column('total_invoices', sa.Integer(), nullable=True),
    sa.Column('total_customers', sa.Integer(), nullable=True),
    sa.Column('average_invoice_value', sa.Float(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('achievement_percent', sa.Float(), nullable=True),
    sa.Column('incentive_earned', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sales_perf', 'sales_performance', ['employee_id', 'period_year', 'period_month'], unique=False)
    op.create_table('pay_slips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('salary_record_id', sa.String(length=36), nullable=False),
    sa.Column('slip_number', sa.String(length=50), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('earnings_json', sa.Text(), nullable=True),
    sa.Column('deductions_json', sa.Text(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_record_id'], ['salary_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slip_number')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processed_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_number')
    )
    op.create_table('tax_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('return_id', sa.String(length=36), nullable=True),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('taxable_amount', sa.Float(), nullable=False),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('total_tax', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['medical_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_records')
    op.drop_table('payment_transactions')
    op.drop_table('pay_slips')
    op.drop_index('idx_sales_perf', table_name='sales_performance')
    op.drop_table('sales_performance')
    op.drop_index('idx_pf_period', table_name='pf_records')
    op.drop_table('pf_records')
    op.drop_table('notification_logs')
    op.drop_index('idx_esi_period', table_name='esi_records')
    op.drop_table('esi_records')
    op.drop_table('customer_addresses')
    op.drop_table('customer_activity_logs')
    op.drop_index('idx_wh_shop_map', table_name='warehouse_shop_map')
    op.drop_table('warehouse_shop_map')
    op.drop_table('vat_reports')
    op.drop_table('tax_settings')
    op.drop_table('shop_settings')
    op.drop_index('idx_ledger_date', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('income_expense')
    op.drop_table('gst_reports')
    op.drop_index('idx_billing_seq', table_name='billing_sequences')
    op.drop_table('billing_sequences')
    op.drop_table('warehouse_settings')
    op.drop_table('stock_adjustments')
    op.drop_table('expiry_alerts')
    op.drop_index('idx_stock_threshold', table_name='stock_thresholds')
    op.drop_table('stock_thresholds')
    op.drop_table('medicine_pricing_history')
    op.drop_index('idx_file_entity', table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_table('feature_flags')
    op.drop_table('application_settings')
    op.drop_table('unit_master')
    op.drop_table('notification_templates')
    op.drop_table('medicine_categories')
    op.drop_table('hsn_master')
    # ### end Alembic commands ###
